window.SPECTRUM_REGISTRY = [
  {
    id: "jp",
    title_zh: "日本政治・社会価値観スペクトラム診断",
    title_en: "Japan Political Spectrum Test",
    region: "Japan",
    href: "/private-homepage/jp-spectrum/",
    status: "available",
    question_count: 100,
    axis_count: 10,
    languages: ["中文"],
    summary: "面向日本政治现状的 10 维度测试，覆盖福利、财政、安保、外交、外国人、社会、能源、地方与公民自由。",
  },
  {
    id: "us",
    title_zh: "美国政治・社会价值观光谱测试",
    title_en: "United States Political Spectrum Test",
    region: "United States",
    href: "/private-homepage/us-spectrum/",
    status: "available",
    question_count: 160,
    axis_count: 10,
    languages: ["中文", "English"],
    summary: "中英双语美国版，覆盖经济、国家能力、自由秩序、文化、移民、种族、制度、外交、军事与气候。",
  },
  {
    id: "cn",
    title_zh: "中国大陆政治光谱测试",
    title_en: "China Mainland Political Spectrum Test",
    region: "China",
    href: "/private-homepage/cn-spectrum/",
    status: "available",
    question_count: 160,
    axis_count: 8,
    languages: ["简体中文"],
    summary: "需访问密码。以 8 个政策维度理解经济、福利、制度、秩序、国家认同、文化、技术治理与生态发展，并与社会思潮理想类型对照。",
  },
  {
    id: "fr",
    title_zh: "法国政治光谱测试",
    title_en: "France Political Spectrum Test",
    region: "France",
    href: "/private-homepage/fr-spectrum/",
    status: "available",
    question_count: 160,
    axis_count: 8,
    languages: ["中文"],
    summary: "公开法国版增强测试，覆盖经济分配、欧洲/主权、共和国身份、秩序自由、生态生产、制度民粹、外交战略与地方社会。",
  },
  {
    id: "uk",
    title_zh: "英国政治光谱测试",
    title_en: "United Kingdom Political Spectrum Test",
    region: "United Kingdom",
    href: "/private-homepage/uk-spectrum/",
    status: "available",
    question_count: 160,
    axis_count: 10,
    languages: ["中文"],
    summary: "公开英国版增强测试，覆盖财政福利、市场劳动、移民身份、Brexit、Union/Devolution、气候能源、制度改革与外交安全。",
  },
  {
    id: "de",
    title_zh: "德国政治光谱测试",
    title_en: "Germany Political Spectrum Test",
    region: "Germany",
    href: "/private-homepage/de-spectrum/",
    status: "available",
    question_count: 160,
    axis_count: 10,
    languages: ["中文"],
    summary: "公开德国版增强测试，覆盖社会国家、债务刹车、气候能源、移民庇护、文化自由、欧盟、外交安全、自由宪政、地区差异与国家现代化。",
  },
  {
    id: "global",
    title_zh: "全球意识形态测试",
    title_en: "Global Ideology Test",
    region: "Global",
    href: "#future",
    status: "planned",
    question_count: null,
    axis_count: null,
    languages: ["中文", "English"],
    summary: "预留：跨国家比较的意识形态坐标，不绑定具体选举或党派。",
  },
  {
    id: "europe",
    title_zh: "欧洲政治光谱测试",
    title_en: "Europe Political Spectrum Test",
    region: "Europe",
    href: "#future",
    status: "planned",
    question_count: null,
    axis_count: null,
    languages: ["中文", "English"],
    summary: "预留：福利国家、欧盟统合、民族国家、移民、气候与外交安全。",
  },
  {
    id: "korea",
    title_zh: "韩国政治光谱测试",
    title_en: "Korea Political Spectrum Test",
    region: "Korea",
    href: "#future",
    status: "planned",
    question_count: null,
    axis_count: null,
    languages: ["中文"],
    summary: "预留：南北关系、财阀改革、劳工、性别、住房、外交安保与世代政治。",
  },
  {
    id: "taiwan",
    title_zh: "台湾政治光谱测试",
    title_en: "Taiwan Political Spectrum Test",
    region: "Taiwan",
    href: "/private-homepage/tw-spectrum/",
    status: "available",
    question_count: 160,
    axis_count: 8,
    languages: ["中文"],
    summary: "需访问密码。简中台湾版增强测试，覆盖身份、两岸、安全、经济、住房、文化、能源与民主治理，并提供丰富结果解读。",
  },
];
