window.DE_SPECTRUM_DATA = (() => {
  const version = "de-spectrum-2026.06-v0.1";

  const axes = [
    {
      id: "ECO",
      short: "ECO",
      name: "经济再分配",
      negativeLabel: "市场/低再分配/企业竞争力",
      positiveLabel: "社会国家/再分配/劳工保护",
      color: "#cf5549",
      weight: 1.2,
      description: "衡量税收、福利、工资、劳工保护、公共服务和阶层流动之间的取向。",
    },
    {
      id: "FISC",
      short: "FISC",
      name: "财政投资",
      negativeLabel: "债务刹车/财政纪律/减税空间",
      positiveLabel: "公共投资/基础设施/财政扩张",
      color: "#b47a18",
      weight: 1.1,
      description: "衡量债务刹车、公共投资、住房、交通、教育和地方财政之间的取向。",
    },
    {
      id: "CLIM",
      short: "CLIM",
      name: "气候能源",
      negativeLabel: "成本控制/技术中立/生产优先",
      positiveLabel: "快速绿色转型/生态约束",
      color: "#2f8f6f",
      weight: 1,
      description: "衡量气候目标、能源价格、工业竞争力、农业与生态政策之间的取向。",
    },
    {
      id: "MIG",
      short: "MIG",
      name: "移民庇护",
      negativeLabel: "限制庇护/强边境/快速遣返",
      positiveLabel: "开放融合/人道庇护/合法路径",
      color: "#7656a7",
      weight: 1.15,
      description: "衡量庇护、入籍、劳动力移民、边境控制和融合政策之间的取向。",
    },
    {
      id: "CULT",
      short: "GAL",
      name: "文化自由",
      negativeLabel: "传统秩序/国家认同/TAN",
      positiveLabel: "GAL 进步/多元/公民自由",
      color: "#9c5aa6",
      weight: 1,
      description: "衡量性别平等、LGBTQ+、宗教自由、历史记忆和社会价值议题。",
    },
    {
      id: "EU",
      short: "EU",
      name: "欧盟一体化",
      negativeLabel: "国家主权/欧盟怀疑/边界优先",
      positiveLabel: "欧洲一体化/共同规则",
      color: "#435bb8",
      weight: 1,
      description: "衡量德国在欧盟、欧元区、共同财政、边界和欧洲身份中的定位。",
    },
    {
      id: "SEC",
      short: "SEC",
      name: "外交安全",
      negativeLabel: "克制/和平主义/对俄妥协",
      positiveLabel: "NATO/援乌/国防投入",
      color: "#c0613a",
      weight: 0.95,
      description: "衡量 NATO、援乌、对俄政策、国防预算、军备出口和战略现实主义。",
    },
    {
      id: "DEM",
      short: "DEM",
      name: "自由宪政",
      negativeLabel: "反建制多数主义/强人授权",
      positiveLabel: "自由宪政/法治/制度制衡",
      color: "#5f7891",
      weight: 1.1,
      description: "衡量宪法法院、媒体、公民社会、反极端主义、政党禁令和议会协商。",
    },
    {
      id: "REG",
      short: "REG",
      name: "地区团结",
      negativeLabel: "财政自担/增长中心/地方竞争",
      positiveLabel: "东西德与城乡补偿/区域公共投资",
      color: "#247c9b",
      weight: 0.9,
      description: "衡量东西德、城市乡村、教育机会、地方公共服务和区域不平等。",
    },
    {
      id: "MOD",
      short: "MOD",
      name: "现代化国家能力",
      negativeLabel: "小政府/监管谨慎/渐进守成",
      positiveLabel: "数字化/产业政策/行政能力",
      color: "#8f6b2f",
      weight: 0.9,
      description: "衡量数字国家、产业政策、行政改革、治安能力、基础设施和技术治理。",
    },
  ];

  const topics = [
    { id: "A", axis: "ECO", title: "经济分配：再分配/劳工 vs 市场/企业", summary: "税收、工资、共同决定、福利国家和企业竞争力。" },
    { id: "B", axis: "FISC", title: "财政国家：公共投资 vs 债务刹车", summary: "债务刹车、公共投资、铁路、学校、国防和财政纪律。" },
    { id: "C", axis: "CLIM", title: "气候能源：绿色转型 vs 成本/技术中立", summary: "气候目标、能源价格、核能、煤炭退出、农业和工业竞争力。" },
    { id: "D", axis: "MIG", title: "移民与庇护：开放融合 vs 限制控制", summary: "庇护、边境、遣返、劳动力移民、入籍和融合。" },
    { id: "E", axis: "CULT", title: "文化自由：GAL 进步 vs 传统秩序", summary: "性别平等、LGBTQ+、宗教自由、教育和社会价值。" },
    { id: "F", axis: "EU", title: "欧盟与主权：欧洲一体化 vs 国家主权", summary: "欧盟、欧元区、共同财政、边界、扩大和德国责任。" },
    { id: "G", axis: "SEC", title: "外交安全：NATO/援乌 vs 和平主义/克制", summary: "NATO、乌克兰、俄罗斯、国防预算、军备出口和战略自主。" },
    { id: "H", axis: "DEM", title: "民主制度：宪政自由主义 vs 反建制多数主义", summary: "法治、宪法法院、媒体、公民社会、极端主义和抗议权。" },
    { id: "I", axis: "REG", title: "东西德、城市乡村与地区不平等", summary: "地区差异、公共服务、交通、地方身份和机会结构。" },
    { id: "J", axis: "MOD", title: "现代化、数字化与产业政策", summary: "数字政府、工业政策、创新、官僚制和技术基础设施。" },
    { id: "K", axis: "ECO", title: "社会福利、养老与家庭", summary: "养老金、儿童贫困、护理、家庭政策和社会保险。" },
    { id: "L", axis: "FISC", title: "住房、交通与生活成本", summary: "租金、住房建设、公共交通、能源价格和城市成本。" },
    { id: "M", axis: "REG", title: "教育、阶层流动与青年政治", summary: "教育公平、职业教育、大学、青年参与和代际机会。" },
    { id: "N", axis: "MOD", title: "法治、治安与国家能力", summary: "警察、法院、反恐、行政效率、国家执行力和基本权利。" },
    { id: "O", axis: "CULT", title: "国家认同、历史记忆与公民共同体", summary: "德国身份、历史责任、移民共同体、纪念文化和公民身份。" },
    { id: "P", axis: "DEM", title: "综合治理与政治风格", summary: "妥协、专家、民粹、政党政治、透明度和民主协商。" },
  ];

  const itemBank = {
    A: [
      ["德国应通过更高财富税、遗产税和资本收益税来减轻中低收入群体负担。", 1, ["税收", "财富"]],
      ["德国经济更需要减税和放松监管，而不是扩大再分配。", -1, ["企业", "监管"]],
      ["工会和集体谈判应在工资、工时和工作条件上拥有更强影响力。", 1, ["工会", "工资"]],
      ["过强的劳工保护会削弱中小企业雇佣意愿。", -1, ["劳工", "中小企业"]],
      ["最低工资应继续显著提高，以抵消通胀和住房成本。", 1, ["最低工资", "生活成本"]],
      ["工资主要应由市场和生产率决定，而不是政治设定。", -1, ["工资", "市场"]],
      ["关键公共服务不应按利润逻辑运行，国家应保留更强控制权。", 1, ["公共服务", "国家"]],
      ["扩大福利会削弱个人责任和就业激励。", -1, ["福利", "责任"]],
      ["大型企业董事会中的员工共同决定权应继续加强。", 1, ["共同决定", "企业治理"]],
      ["德国竞争力的核心是让企业更容易投资、雇佣和扩张。", -1, ["竞争力", "投资"]],
    ],
    B: [
      ["债务刹车应改革，让国家能大规模投资铁路、学校、住房和数字基础设施。", 1, ["债务刹车", "投资"]],
      ["债务刹车是德国财政可信度的核心，不应轻易放松。", -1, ["债务刹车", "纪律"]],
      ["在基础设施老化时，公共投资比短期平衡预算更重要。", 1, ["基础设施", "预算"]],
      ["政府借债会把今天的政治成本转嫁给下一代。", -1, ["代际", "债务"]],
      ["地方政府需要更稳定的联邦财政支持来维持公共服务。", 1, ["地方财政", "公共服务"]],
      ["地方政府应更多通过优先级调整而不是等待联邦转移支付解决问题。", -1, ["地方财政", "效率"]],
      ["气候转型和国防转型需要专项基金或例外规则。", 1, ["专项基金", "转型"]],
      ["专项基金容易绕开正常预算纪律，应尽量少用。", -1, ["专项基金", "预算"]],
      ["德国应把公共投资视为长期资产，而不只是财政支出。", 1, ["公共投资", "长期"]],
      ["减税和私人投资比政府投资更能推动增长。", -1, ["减税", "增长"]],
    ],
    C: [
      ["德国应坚持更快的减排路径，即使能源和工业成本短期上升。", 1, ["减排", "成本"]],
      ["气候政策必须更重视家庭账单和工业竞争力。", -1, ["能源价格", "工业"]],
      ["煤炭退出、热泵和建筑节能应继续加速推进。", 1, ["煤炭退出", "建筑"]],
      ["气候转型如果过快，会加剧民众对政治的不信任。", -1, ["信任", "转型"]],
      ["德国应通过公共补贴帮助低收入家庭完成绿色改造。", 1, ["补贴", "公平"]],
      ["补贴不能掩盖绿色政策本身过度昂贵的问题。", -1, ["补贴", "成本"]],
      ["农业、交通和工业都应接受更严格的生态约束。", 1, ["农业", "工业"]],
      ["环保标准不应压垮农民、司机和能源密集型企业。", -1, ["农业", "企业"]],
      ["国家应优先扩建可再生能源、电网和储能。", 1, ["可再生能源", "电网"]],
      ["气候政策应保持技术中立，不应排除任何低碳方案。", -1, ["技术中立", "能源"]],
    ],
    D: [
      ["德国应为庇护申请者提供更安全、快速和人道的程序。", 1, ["庇护", "人道"]],
      ["德国需要明显收紧庇护和移民规则，减少吸引效应。", -1, ["庇护", "限制"]],
      ["劳动力短缺意味着德国应扩大合法移民和技能移民通道。", 1, ["劳动力", "技能移民"]],
      ["移民数量已经超过德国公共服务和住房系统承受能力。", -1, ["公共服务", "住房"]],
      ["长期居住、工作和学习的人应更容易获得公民身份。", 1, ["入籍", "融合"]],
      ["入籍和长期居留应设置更严格的语言、收入和价值认同条件。", -1, ["入籍", "条件"]],
      ["融合政策应把教育、住房和就业放在身份审查之前。", 1, ["融合", "教育"]],
      ["快速遣返无居留权者是恢复政策信任的关键。", -1, ["遣返", "信任"]],
      ["德国社会可以容纳多元宗教和文化，只要基本法得到遵守。", 1, ["多元文化", "基本法"]],
      ["平行社会问题说明移民政策必须更强调同化和边界。", -1, ["平行社会", "同化"]],
    ],
    E: [
      ["学校和公共机构应更积极保护 LGBTQ+、性别平等和反歧视教育。", 1, ["LGBTQ+", "教育"]],
      ["性别和身份议题在公共政策中已经被过度强调。", -1, ["性别", "身份"]],
      ["宗教少数群体在公共生活中的和平表达应受到保护。", 1, ["宗教", "自由"]],
      ["德国应更明确维护主流文化规范和社会秩序。", -1, ["传统", "秩序"]],
      ["反种族主义政策应正视住房、警务和教育中的结构性不平等。", 1, ["反歧视", "结构"]],
      ["把社会问题过度解释为结构性歧视会削弱个人责任。", -1, ["责任", "歧视"]],
      ["公共媒体和学校应更多呈现多元家庭与生活方式。", 1, ["媒体", "家庭"]],
      ["传统家庭和社区价值应在教育政策中得到更高位置。", -1, ["家庭", "教育"]],
      ["数字平台上的仇恨言论需要更严格监管。", 1, ["仇恨言论", "平台"]],
      ["言论自由应容忍更多冒犯性观点，而不是迅速监管。", -1, ["言论自由", "监管"]],
    ],
    F: [
      ["德国的长期利益在于更深的欧盟一体化和共同决策。", 1, ["欧盟", "一体化"]],
      ["德国应把更多关键政策决定权留在本国议会。", -1, ["主权", "议会"]],
      ["欧元区需要更强共同财政工具来应对危机。", 1, ["欧元区", "财政"]],
      ["德国纳税人不应为其他成员国的财政问题承担过多责任。", -1, ["财政责任", "欧元"]],
      ["欧盟共同气候、数字和贸易规则能保护德国利益。", 1, ["欧盟规则", "贸易"]],
      ["布鲁塞尔监管已经过多限制德国企业和农民。", -1, ["监管", "农民"]],
      ["欧洲边界和庇护政策应通过共同机制处理。", 1, ["边界", "庇护"]],
      ["移民和边境政策应更多由德国自己决定。", -1, ["边境", "主权"]],
      ["欧盟扩大应服务于民主与安全共同体，即使改革成本较高。", 1, ["欧盟扩大", "安全"]],
      ["欧盟扩大必须非常谨慎，以免削弱制度效率和社会标准。", -1, ["欧盟扩大", "效率"]],
    ],
    G: [
      ["德国应继续支持乌克兰，包括军事援助和长期安全承诺。", 1, ["乌克兰", "援助"]],
      ["向乌克兰提供重武器会增加德国被拖入战争的风险。", -1, ["重武器", "风险"]],
      ["德国需要更高国防预算，以承担欧洲安全责任。", 1, ["国防预算", "责任"]],
      ["提高军费会挤压社会和气候投资，应谨慎。", -1, ["军费", "社会投资"]],
      ["NATO 仍是德国安全的核心支柱。", 1, ["NATO", "安全"]],
      ["德国应减少对美国安全承诺的依赖，走更克制的路线。", -1, ["美国", "克制"]],
      ["对俄罗斯的政策必须以威慑和制裁为基础。", 1, ["俄罗斯", "制裁"]],
      ["欧洲安全最终需要和俄罗斯恢复谈判框架。", -1, ["俄罗斯", "谈判"]],
      ["德国应更愿意向盟友提供军备和防务技术。", 1, ["军备出口", "盟友"]],
      ["德国历史经验要求外交上保持军事克制。", -1, ["历史", "克制"]],
    ],
    H: [
      ["宪法法院、独立媒体和公民社会是德国民主的核心护栏。", 1, ["宪政", "媒体"]],
      ["当前政治精英经常用制度话语压制普通民众的不满。", -1, ["反建制", "民意"]],
      ["面对极端主义，国家应依法采取更强防御性民主措施。", 1, ["极端主义", "防御民主"]],
      ["政党禁令或情报机构介入容易被滥用，应极其谨慎。", -1, ["政党禁令", "情报"]],
      ["公共媒体应保持强独立性，即使经常受到党派批评。", 1, ["公共媒体", "独立"]],
      ["公共媒体体制需要大幅削减和去政治化。", -1, ["公共媒体", "改革"]],
      ["抗议权和反对派权利不应因安全理由被过度限制。", 1, ["抗议权", "反对派"]],
      ["当街头抗议持续扰乱社会秩序时，政府应更快恢复控制。", -1, ["抗议", "秩序"]],
      ["议会妥协比公投式情绪动员更适合德国制度。", 1, ["议会", "妥协"]],
      ["重大议题应更多交由全民公投，而不是政党谈判。", -1, ["公投", "政党"]],
    ],
    I: [
      ["东西德差异仍然需要长期公共投资和政治承认。", 1, ["东西德", "投资"]],
      ["统一已经过去很久，东部不应总以特殊待遇自我定位。", -1, ["统一", "责任"]],
      ["农村和小城市的交通、医疗、宽带和学校应得到更高优先级。", 1, ["乡村", "公共服务"]],
      ["资源应优先投向最能产生增长的城市和产业集群。", -1, ["城市", "增长"]],
      ["东部选民的不满不能简单归因于极端主义。", 1, ["东部", "不满"]],
      ["地方不满经常被政治力量夸大，不能成为反制度借口。", -1, ["地方", "制度"]],
      ["联邦应更积极缩小地区工资、财富和公共服务差距。", 1, ["工资", "差距"]],
      ["地区间竞争能倒逼地方政府提高效率。", -1, ["竞争", "效率"]],
      ["住房和交通政策应更多照顾郊区与通勤者。", 1, ["郊区", "通勤"]],
      ["高密度城市生活是更高效、低碳和创新的方向。", -1, ["城市", "低碳"]],
    ],
    J: [
      ["德国需要更主动的产业政策，扶持芯片、电池、AI 和绿色制造。", 1, ["产业政策", "创新"]],
      ["国家挑选赢家往往效率低，创新应主要交给市场。", -1, ["市场", "创新"]],
      ["数字政府和统一数据标准应成为联邦改革重点。", 1, ["数字政府", "数据"]],
      ["数字化不能成为扩大国家数据收集的理由。", -1, ["隐私", "数字化"]],
      ["审批、规划和基础设施建设需要更强中央协调。", 1, ["审批", "基础设施"]],
      ["过度中央协调会忽视地方经验和企业自主。", -1, ["地方", "企业"]],
      ["德国应建立更快的公共采购和技术试点机制。", 1, ["采购", "试点"]],
      ["公共部门追逐新技术容易浪费预算。", -1, ["预算", "技术"]],
      ["能源、铁路、国防和数字网络都需要国家能力升级。", 1, ["国家能力", "网络"]],
      ["现代化不应成为扩大官僚机构和监管层级的借口。", -1, ["官僚", "监管"]],
    ],
    K: [
      ["养老金和护理体系应通过更强社会保险和税收保障体面生活。", 1, ["养老金", "护理"]],
      ["养老金改革必须更重视缴费负担和人口老龄化现实。", -1, ["养老金", "老龄化"]],
      ["儿童贫困是德国社会国家最需要优先解决的问题之一。", 1, ["儿童贫困", "家庭"]],
      ["家庭政策应避免变成无限扩大现金补贴。", -1, ["家庭", "补贴"]],
      ["护理、幼托和教育应被视为公共基础设施。", 1, ["幼托", "公共服务"]],
      ["家庭照护和私人责任不应完全被国家服务取代。", -1, ["家庭", "责任"]],
      ["德国应通过更强租房补贴和社会住房保护低收入家庭。", 1, ["住房", "低收入"]],
      ["社会政策应更严格防止福利依赖。", -1, ["福利依赖", "就业"]],
      ["失业者应获得更稳定培训和转岗支持，而不只是制裁。", 1, ["失业", "培训"]],
      ["就业中心应更坚决要求可工作者接受合理工作。", -1, ["就业中心", "制裁"]],
    ],
    L: [
      ["大城市租金压力需要更强租金管制和公共住房建设。", 1, ["租金", "住房"]],
      ["租金管制会抑制住房供给，建设和简化审批更重要。", -1, ["供给", "审批"]],
      ["Deutschlandticket 和地方公共交通应获得长期财政保障。", 1, ["公共交通", "票价"]],
      ["交通补贴应更精准，不能长期扩大财政负担。", -1, ["补贴", "交通"]],
      ["能源价格上涨时，国家应优先保护低收入家庭。", 1, ["能源价格", "补贴"]],
      ["普遍性能源补贴会削弱节能激励。", -1, ["能源", "节能"]],
      ["住房政策应要求开发商承担更多社会住房和基础设施责任。", 1, ["开发商", "社会住房"]],
      ["过多开发商义务会让建设成本更高、速度更慢。", -1, ["建设成本", "开发"]],
      ["铁路、公交和自行车网络应优先于扩大道路容量。", 1, ["铁路", "自行车"]],
      ["汽车仍是很多地区现实必需品，政策不应惩罚开车者。", -1, ["汽车", "乡村"]],
    ],
    M: [
      ["教育资金应更多流向弱势地区和移民背景学生集中的学校。", 1, ["教育公平", "学校"]],
      ["学校质量主要取决于管理、纪律和家庭责任，而不是再分配。", -1, ["学校", "责任"]],
      ["德国应减少教育机会对父母阶层和地区的依赖。", 1, ["阶层", "机会"]],
      ["过度追求结果平等会降低学校标准。", -1, ["标准", "平等"]],
      ["职业教育和大学都应获得更多公共投资。", 1, ["职业教育", "大学"]],
      ["大学扩张不应牺牲双元制职业教育的优势。", -1, ["大学", "双元制"]],
      ["青年租房、交通和培训压力需要更强国家支持。", 1, ["青年", "生活成本"]],
      ["青年政策不能只靠补贴，应鼓励更早就业和独立。", -1, ["青年", "就业"]],
      ["学校应更早、更系统地教数字能力、媒体素养和民主教育。", 1, ["数字教育", "民主"]],
      ["学校已经承担太多社会任务，应回到基础知识和纪律。", -1, ["基础知识", "纪律"]],
    ],
    N: [
      ["法院、移民局和地方行政需要更多人员和数字化来提高执行力。", 1, ["行政", "法院"]],
      ["国家能力问题首先是程序过多，不是人员太少。", -1, ["程序", "效率"]],
      ["面对有组织犯罪和极端主义，警察和情报机构需要更强工具。", 1, ["警察", "极端主义"]],
      ["安全机构扩权必须受到严格司法监督。", -1, ["监督", "权利"]],
      ["德国应更快执行遣返、制裁和法院判决。", 1, ["执行力", "遣返"]],
      ["快速执行不能牺牲程序正义和个人权利。", -1, ["程序正义", "权利"]],
      ["关键基础设施、铁路和能源网络需要更强国家保护。", 1, ["基础设施", "安全"]],
      ["国家安全名义不能无限扩大监管和审查。", -1, ["国家安全", "审查"]],
      ["联邦和州之间应减少责任推诿，建立更清晰指挥链。", 1, ["联邦", "指挥链"]],
      ["德国联邦制的分散性本身有助于防止权力集中。", -1, ["联邦制", "制衡"]],
    ],
    O: [
      ["德国身份可以建立在基本法、民主和开放公民身份之上。", 1, ["基本法", "公民身份"]],
      ["德国需要更强烈强调语言、文化传统和国家归属感。", -1, ["语言", "传统"]],
      ["历史责任应继续塑造德国对反犹主义、种族主义和战争的敏感性。", 1, ["历史责任", "反犹"]],
      ["德国公共文化有时过度被罪责记忆束缚。", -1, ["记忆文化", "国家认同"]],
      ["移民后代应被更明确视为德国共同体的一部分。", 1, ["移民后代", "共同体"]],
      ["没有充分融入德国价值和语言的人不应轻易获得政治成员资格。", -1, ["融入", "成员资格"]],
      ["纪念纳粹罪行和东德独裁仍是民主教育的重要基础。", 1, ["纪念", "民主教育"]],
      ["德国也应更自信地表达民族利益和正常国家身份。", -1, ["民族利益", "正常国家"]],
      ["多元文化可以和共同的宪法爱国主义并存。", 1, ["多元", "宪法爱国主义"]],
      ["共同身份比多元差异更需要被政治强调。", -1, ["共同身份", "差异"]],
    ],
    P: [
      ["德国需要更多跨党派妥协，而不是把政治变成道德战争。", 1, ["妥协", "协商"]],
      ["当前危机需要明确方向感，过度妥协会维持停滞。", -1, ["领导力", "危机"]],
      ["专家机构和独立委员会在复杂政策中应发挥重要作用。", 1, ["专家", "委员会"]],
      ["专家政治经常脱离普通人的现实经验。", -1, ["专家政治", "民众"]],
      ["政党应更透明披露资金、游说和候选人筛选机制。", 1, ["透明", "政党"]],
      ["过度透明和程序要求会让政治更加僵硬。", -1, ["程序", "效率"]],
      ["社交媒体上的愤怒动员正在伤害德国民主。", 1, ["社交媒体", "民主"]],
      ["传统政党把民众愤怒称为民粹，往往是在逃避问题。", -1, ["民粹", "政党"]],
      ["政治测试的目标应是帮助用户理解自己，而不是告诉用户支持谁。", 1, ["方法", "解释"]],
      ["在高度危机时期，政治中立的技术性表达往往掩盖真正冲突。", -1, ["冲突", "中立"]],
    ],
  };

  const questions = topics.flatMap((topic) =>
    itemBank[topic.id].map(([textZh, polarity, tags], index) => ({
      id: `${topic.id}-${String(index + 1).padStart(2, "0")}`,
      axis: topic.axis,
      topic: topic.id,
      textZh,
      polarity,
      weight: 1,
      tags,
    })),
  );

  const idsByTopic = (topicId, count) => questions
    .filter((question) => question.topic === topicId)
    .slice(0, count)
    .map((question) => question.id);
  const idsByAxis = (axisId, count) => questions
    .filter((question) => question.axis === axisId)
    .slice(0, count)
    .map((question) => question.id);

  function scores(values) {
    return Object.fromEntries(axes.map((axis, index) => [axis.id, values[index]]));
  }

  function profile(id, name, short, status, camp, values, note, confidence, uncertainty, regions = ["Germany"], regionAffinity = {}) {
    return {
      id,
      name,
      short,
      status,
      camp,
      scores: scores(values),
      note,
      confidence,
      uncertainty,
      regions,
      regionAffinity,
      stability: confidence < 45 ? "low" : "medium",
    };
  }

  const profiles = [
    profile("spd", "Sozialdemokratische Partei Deutschlands (SPD)", "SPD", "bundestag", "social_democrat", [68, 66, 62, 64, 70, 75, 68, 80, 72, 70], "社会民主、劳工保护、公共投资、亲欧与现实主义安全政策。", 78, 12),
    profile("cdu", "Christlich Demokratische Union (CDU)", "CDU", "bundestag", "conservative", [42, 45, 45, 38, 42, 65, 76, 72, 56, 60], "基民盟主流：市场经济、财政纪律、亲欧保守与强安全政策。", 78, 13, ["Germany", "West", "Rural"]),
    profile("csu", "Christlich-Soziale Union in Bayern (CSU)", "CSU", "bundestag", "christian_social", [45, 50, 42, 30, 35, 58, 76, 68, 64, 60], "巴伐利亚区域保守、社会市场经济、强边境和强地方身份。", 76, 14, ["Germany", "West", "Rural"], { Rural: 2 }),
    profile("gruene", "Bündnis 90/Die Grünen", "Grüne", "bundestag", "green", [72, 72, 92, 82, 90, 88, 72, 86, 76, 78], "绿色转型、城市自由主义、亲欧与近年更现实主义的安全政策。", 78, 12, ["Germany", "Urban"], { Urban: 4 }),
    profile("fdp", "Freie Demokratische Partei (FDP)", "FDP", "extra_parliamentary", "liberal", [25, 25, 48, 62, 75, 72, 70, 80, 45, 82], "自由市场、债务刹车、公民自由、数字化和亲欧自由主义。", 72, 15, ["Germany", "West", "Urban"]),
    profile("afd", "Alternative für Deutschland (AfD)", "AfD", "bundestag", "national_right", [35, 30, 10, 5, 8, 8, 45, 15, 38, 35], "民族保守/右翼民粹、强反移民、欧盟怀疑、反绿色转型；相关法律与政治争议以公开资料为准。", 68, 20, ["Germany", "East", "Rural"], { East: 5, Rural: 2 }),
    profile("linke", "Die Linke", "Linke", "bundestag", "left", [88, 85, 78, 85, 88, 55, 18, 78, 82, 60], "民主社会主义、再分配、租房与福利、和平主义和进步文化。", 72, 16, ["Germany", "East", "Urban"], { East: 2, Urban: 2 }),
    profile("bsw", "Bündnis Sahra Wagenknecht (BSW)", "BSW", "bundestag", "communitarian", [78, 75, 45, 25, 30, 35, 15, 45, 72, 45], "左翼经济、文化保守、和平主义/对俄妥协、反建制和国家能力诉求。", 58, 24, ["Germany", "East", "Rural"], { East: 4 }),
    profile("freie_waehler", "Freie Wähler", "FW", "minor_party", "regional", [45, 45, 42, 40, 45, 55, 65, 60, 72, 55], "地方主义、中小企业、财政谨慎、务实保守和区域公共服务。", 52, 22, ["Germany", "Rural"], { Rural: 4 }),
    profile("ssw", "Südschleswigscher Wählerverband (SSW)", "SSW", "minority_party", "regional", [70, 70, 75, 82, 85, 85, 62, 82, 94, 68], "丹麦与弗里斯兰少数民族政党，社会自由、亲欧、强地区与少数群体保护。", 64, 18, ["Germany", "West"], { West: 2 }),
    profile("tierschutz", "Partei Mensch Umwelt Tierschutz", "Tierschutz", "minor_party", "green", [72, 72, 92, 78, 86, 76, 38, 76, 72, 62], "动物保护、生态、社会福利与进步文化，小党坐标为低置信估计。", 42, 30, ["Germany", "Urban"]),
    profile("diebasis", "dieBasis", "dieBasis", "minor_party", "minor", [45, 42, 35, 35, 38, 28, 20, 25, 45, 30], "反建制、直接民主、疫情政策反弹和制度怀疑色彩，低置信估计。", 34, 34),
    profile("die_partei", "Die PARTEI", "PARTEI", "minor_party", "minor", [66, 62, 72, 78, 88, 72, 35, 70, 60, 62], "讽刺党，坐标只能按公开表达的左翼自由主义倾向启发式估计。", 32, 36, ["Germany", "Urban"]),
    profile("team_todenhoefer", "Team Todenhöfer", "Team T.", "minor_party", "minor", [58, 55, 52, 62, 60, 48, 12, 45, 55, 48], "反战、反干预、反建制与人道主义表达，低置信估计。", 36, 34),
    profile("piraten", "Piratenpartei Deutschland", "Piraten", "minor_party", "liberal", [55, 58, 70, 85, 95, 80, 45, 92, 68, 92], "数字权利、隐私、开放文化、透明政治和公民自由。", 48, 26, ["Germany", "Urban"], { Urban: 2 }),
    profile("volt", "Volt Deutschland", "Volt", "minor_party", "liberal", [62, 65, 85, 88, 92, 98, 72, 90, 72, 90], "泛欧进步自由主义、数字现代化、气候转型和制度改革。", 52, 24, ["Germany", "Urban"], { Urban: 3 }),
    profile("oekdp", "Ökologisch-Demokratische Partei (ÖDP)", "ÖDP", "minor_party", "green", [58, 60, 88, 65, 65, 70, 50, 75, 78, 58], "生态保守、反增长主义、家庭与地方共同体取向。", 46, 28, ["Germany", "Rural"]),
    profile("pdv", "Partei der Humanisten", "PdH", "minor_party", "liberal", [42, 42, 68, 78, 88, 78, 65, 86, 55, 88], "世俗人文主义、科学理性、公民自由和技术乐观，低置信估计。", 40, 30, ["Germany", "Urban"]),
    profile("buendnis_c", "Bündnis C", "Bündnis C", "minor_party", "minor", [38, 35, 35, 28, 12, 40, 55, 50, 45, 42], "基督教保守、传统家庭和社会保守，小党低置信估计。", 34, 34),
    profile("bp", "Bayernpartei", "BP", "minor_party", "regional", [42, 42, 42, 32, 35, 38, 55, 55, 84, 48], "巴伐利亚区域主义、保守地方身份和去中心化。", 36, 32, ["Germany", "West", "Rural"], { Rural: 2 }),
    profile("mlpd", "Marxistisch-Leninistische Partei Deutschlands (MLPD)", "MLPD", "minor_party", "left", [98, 92, 78, 82, 75, 35, 5, 42, 76, 55], "马列主义、强再分配和反资本主义，低置信且极端位置估计。", 34, 35),
    profile("menschliche_welt", "Menschliche Welt", "Menschliche Welt", "minor_party", "minor", [65, 62, 70, 72, 76, 55, 8, 55, 68, 48], "和平主义、精神性/人道主义与生态社会倾向，低置信估计。", 32, 36),
    profile("pdf", "Partei des Fortschritts", "PdF", "minor_party", "liberal", [50, 55, 72, 78, 84, 78, 60, 82, 62, 90], "进步自由、数字化与改革主义，小党低置信估计。", 34, 34, ["Germany", "Urban"]),
    profile("sgp", "Sozialistische Gleichheitspartei (SGP)", "SGP", "minor_party", "left", [96, 90, 74, 85, 82, 40, 2, 52, 78, 52], "托派社会主义、反战、反资本主义，小党低置信估计。", 32, 36),
    profile("bueso", "Bürgerrechtsbewegung Solidarität (BüSo)", "BüSo", "minor_party", "minor", [55, 62, 35, 45, 35, 20, 18, 30, 55, 48], "拉鲁什传统相关小党，反建制和地缘政治立场特殊，极低置信。", 26, 40),
    profile("buendnis_deutschland", "Bündnis Deutschland", "BD", "minor_party", "conservative", [32, 30, 28, 18, 25, 32, 62, 45, 45, 48], "民族自由保守、强边境、市场经济和反绿色政策，低置信估计。", 38, 32, ["Germany", "Rural"]),
    profile("mera25", "MERA25", "MERA25", "minor_party", "left", [86, 84, 82, 88, 90, 88, 18, 82, 75, 70], "跨国欧洲左翼、生态、民主改革、反紧缩和亲欧改造。", 40, 30, ["Germany", "Urban"]),
    profile("werteunion", "WerteUnion", "WerteUnion", "minor_party", "national_right", [28, 25, 18, 12, 18, 25, 60, 35, 42, 42], "右翼保守、市场经济、反移民和反绿色转型，低置信估计。", 36, 34, ["Germany", "Rural"], { Rural: 1 }),
    profile("verjuengung", "Partei für schulmedizinische Verjüngungsforschung", "Verjüngung", "minor_party", "minor", [45, 52, 55, 55, 62, 60, 45, 68, 50, 88], "单议题长寿/科研取向，非完整意识形态坐标，极低置信。", 24, 42),

    profile("spd_labour", "SPD 工会/社会国家派", "SPD-L", "faction", "social_democrat", [80, 76, 66, 64, 70, 72, 62, 78, 76, 66], "更强调工资、工会、福利国家和公共投资的 SPD 派系参照。", 52, 24),
    profile("spd_fiscal", "SPD 财政务实派", "SPD-M", "faction", "social_democrat", [60, 55, 58, 60, 66, 75, 70, 78, 66, 70], "更重视财政可持续、执政妥协和中间选民的 SPD 参照。", 50, 24),
    profile("cdu_business", "CDU 经济自由/企业派", "CDU-B", "faction", "conservative", [25, 25, 38, 42, 45, 66, 75, 72, 48, 70], "基民盟内部更偏企业、减税、竞争力和监管松绑的参照。", 50, 24, ["Germany", "West"]),
    profile("cdu_social", "CDU 基督教社会派", "CDU-S", "faction", "conservative", [55, 58, 48, 42, 45, 66, 72, 72, 66, 58], "基民盟内部更偏社会市场经济、家庭和共同体责任的参照。", 48, 26, ["Germany", "West", "Rural"]),
    profile("gruene_realo", "Grüne Realo 现实派", "GR-R", "faction", "green", [66, 66, 84, 78, 86, 88, 78, 86, 70, 82], "绿党内部更重视执政、产业转型和安全现实主义的参照。", 52, 24, ["Germany", "Urban"]),
    profile("gruene_fundi", "Grüne 左翼生态派", "GR-F", "faction", "green", [82, 82, 98, 88, 94, 84, 45, 86, 82, 70], "绿党内部更偏社会运动、生态约束和经济左翼的参照。", 50, 24, ["Germany", "Urban"]),
    profile("fdp_classical", "FDP 古典自由主义派", "FDP-C", "faction", "liberal", [18, 18, 42, 58, 72, 70, 68, 82, 38, 84], "自负责任、减税、债务刹车、市场和公民自由参照。", 48, 26, ["Germany", "West", "Urban"]),
    profile("linke_movement", "Die Linke 社运/租房左翼", "LIN-M", "faction", "left", [92, 88, 84, 92, 94, 62, 18, 82, 84, 62], "租房、反贫困、社运、开放文化和反军事化参照。", 48, 26, ["Germany", "East", "Urban"]),
    profile("afd_national", "AfD 民族保守/右翼民粹派", "AfD-N", "faction", "national_right", [32, 28, 6, 2, 5, 5, 42, 8, 35, 32], "强反移民、强民族认同、反欧盟和反绿色转型参照；敏感法律政治争议以公开资料为准。", 46, 30, ["Germany", "East", "Rural"], { East: 5, Rural: 2 }),
    profile("bsw_communitarian", "BSW 文化保守左翼派", "BSW-C", "faction", "communitarian", [84, 82, 42, 18, 22, 30, 8, 38, 76, 42], "左翼经济、移民限制、文化保守、和平主义和反建制参照。", 44, 32, ["Germany", "East", "Rural"], { East: 4 }),
  ];

  const modes = [
    { id: "quick", label: "快速版", question_count: 40, questionIds: axes.flatMap((axis) => idsByAxis(axis.id, 4)) },
    { id: "standard", label: "标准版", question_count: 80, questionIds: topics.flatMap((topic) => idsByTopic(topic.id, 5)) },
    { id: "full", label: "深度版", question_count: 160, questionIds: questions.map((question) => question.id) },
  ];

  const defaultWeights = Object.fromEntries(axes.map((axis) => [axis.id, axis.weight]));

  const regionViews = [
    {
      id: "Germany",
      label: "德国全国",
      profileRegions: ["Germany"],
      note: "全国视角保留全部内置党派和派系，排序只按你的政策距离与默认权重计算。",
    },
    {
      id: "East",
      label: "东部德国",
      profileRegions: ["Germany", "East"],
      note: "东部视角不会改变你的分数，但会轻微提高更具东部组织或选民结构相关性的参照排序。不要把它理解为地区标签。",
    },
    {
      id: "West",
      label: "西部德国",
      profileRegions: ["Germany", "West"],
      note: "西部视角更强调传统 Volksparteien、基民盟/社民党地方组织、巴伐利亚和西部城市中产结构。",
    },
    {
      id: "Urban",
      label: "城市",
      profileRegions: ["Germany", "Urban"],
      note: "城市视角更容易突出绿党、自由主义、左翼社运和数字/欧洲主义参照，但不改变原始维度分。",
    },
    {
      id: "Rural",
      label: "乡村/小城市",
      profileRegions: ["Germany", "Rural"],
      note: "乡村和小城市视角更强调交通、地方服务、农业、保守共同体和地区公共投资。",
    },
  ];

  const coordinateViews = [
    {
      id: "econ_culture",
      label: "经济 × 文化",
      xAxes: ["ECO", "FISC"],
      yAxes: ["MIG", "CULT", "DEM"],
      xLabel: "市场/债务纪律 ←→ 社会国家/公共投资",
      yLabel: "传统/限制/多数主义 ←→ 开放/自由宪政",
    },
    {
      id: "eu_security",
      label: "欧盟 × 安全",
      xAxes: ["EU"],
      yAxes: ["SEC"],
      xLabel: "主权怀疑 ←→ 欧洲一体化",
      yLabel: "和平克制 ←→ NATO/援乌/国防",
    },
    {
      id: "climate_modern",
      label: "气候 × 现代化",
      xAxes: ["MOD", "FISC"],
      yAxes: ["CLIM"],
      xLabel: "小政府/财政谨慎 ←→ 国家能力/投资",
      yLabel: "成本/技术中立 ←→ 快速绿色转型",
    },
    {
      id: "region_state",
      label: "地区 × 财政",
      xAxes: ["FISC"],
      yAxes: ["REG"],
      xLabel: "债务刹车 ←→ 公共投资",
      yLabel: "增长中心/竞争 ←→ 地区团结",
    },
    {
      id: "dem_migration",
      label: "民主 × 移民",
      xAxes: ["MIG"],
      yAxes: ["DEM"],
      xLabel: "限制控制 ←→ 开放融合",
      yLabel: "反建制授权 ←→ 自由宪政",
    },
  ];

  const matchViews = [
    { id: "all", label: "全部议题", axes: axes.map((axis) => axis.id) },
    { id: "no_eu_security", label: "排除欧盟/外交", axes: ["ECO", "FISC", "CLIM", "MIG", "CULT", "DEM", "REG", "MOD"] },
    { id: "economy", label: "只看经济财政", axes: ["ECO", "FISC", "MOD"] },
    { id: "culture", label: "只看移民文化民主", axes: ["MIG", "CULT", "DEM"] },
    { id: "climate_region", label: "只看气候地区现代化", axes: ["CLIM", "REG", "MOD"] },
    { id: "external", label: "只看欧盟外交", axes: ["EU", "SEC"] },
  ];

  const coalitionViews = [
    { id: "black_red", name: "黑红联盟 CDU/CSU + SPD", members: ["cdu", "csu", "spd"], note: "传统大联合政府式中间路线，经济和社会政策通常需要大幅妥协。" },
    { id: "black_green", name: "黑绿联盟 CDU/CSU + Grüne", members: ["cdu", "csu", "gruene"], note: "保守财政/安全与绿色转型、城市自由主义之间的组合。" },
    { id: "traffic_light", name: "交通灯 SPD + Grüne + FDP", members: ["spd", "gruene", "fdp"], note: "社会民主、绿色自由主义和市场自由主义之间的三方平衡。" },
    { id: "jamaica", name: "牙买加 CDU/CSU + Grüne + FDP", members: ["cdu", "csu", "gruene", "fdp"], note: "保守、绿色和自由市场改革之间的组合。" },
    { id: "red_red_green", name: "红红绿 SPD + Grüne + Linke", members: ["spd", "gruene", "linke"], note: "经济左翼和进步文化更强，但安全外交与财政议题存在张力。" },
    { id: "kenya", name: "肯尼亚 CDU/CSU + SPD + Grüne", members: ["cdu", "csu", "spd", "gruene"], note: "宽泛中间联盟，通常以稳定和妥协为优先。" },
    { id: "black_yellow", name: "黑黄 CDU/CSU + FDP", members: ["cdu", "csu", "fdp"], note: "市场、财政纪律、亲欧和强安全路线较突出。" },
    { id: "left_bsw", name: "经济左翼组合 SPD + Linke + BSW", members: ["spd", "linke", "bsw"], note: "经济再分配相近，但移民、文化和外交安全差异很大。" },
  ];

  const resultLabels = [
    {
      id: "social_dem_european",
      name: "社会国家型亲欧社民派",
      summary: "你重视再分配、公共投资和自由宪政，同时整体支持德国留在欧洲一体化和西方安全框架中。",
      tags: ["社会国家", "亲欧", "自由宪政"],
      rules: [{ axis: "ECO", min: 60 }, { axis: "FISC", min: 58 }, { axis: "EU", min: 62 }, { axis: "DEM", min: 62 }],
    },
    {
      id: "green_liberal",
      name: "绿色城市自由派",
      summary: "你在气候、文化自由、移民开放和欧洲议题上明显进步，同时接受一定国家能力和制度改革。",
      tags: ["绿色转型", "GAL", "亲欧"],
      rules: [{ axis: "CLIM", min: 78 }, { axis: "MIG", min: 68 }, { axis: "CULT", min: 75 }, { axis: "EU", min: 70 }],
    },
    {
      id: "ordoliberal_pro_eu",
      name: "秩序自由主义亲欧改革派",
      summary: "你更重视市场、债务纪律、数字化和制度法治，同时在欧洲与公民自由上保持开放。",
      tags: ["市场", "债务纪律", "数字化"],
      rules: [{ axis: "ECO", max: 42 }, { axis: "FISC", max: 42 }, { axis: "MOD", min: 68 }, { axis: "DEM", min: 65 }],
    },
    {
      id: "christian_democrat",
      name: "基督教民主务实保守派",
      summary: "你偏向财政纪律、社会市场经济、强安全和中度亲欧，在文化与移民议题上较保守但不必然反制度。",
      tags: ["社会市场", "保守", "安全"],
      rules: [{ axis: "ECO", max: 52 }, { axis: "FISC", max: 55 }, { axis: "MIG", max: 48 }, { axis: "SEC", min: 60 }, { axis: "DEM", min: 55 }],
    },
    {
      id: "national_populist",
      name: "民族民粹右派",
      summary: "你高度强调边境、国家主权、传统秩序和反建制动员，对欧盟、移民和绿色转型明显怀疑。",
      tags: ["主权", "边境", "反建制"],
      rules: [{ axis: "MIG", max: 25 }, { axis: "CULT", max: 28 }, { axis: "EU", max: 25 }, { axis: "CLIM", max: 30 }, { axis: "DEM", max: 38 }],
    },
    {
      id: "left_pacifist",
      name: "福利国家和平主义左翼",
      summary: "你强烈支持再分配、福利国家和租房/劳工保护，在外交安全上明显偏克制或反军事化。",
      tags: ["经济左翼", "和平主义", "社会运动"],
      rules: [{ axis: "ECO", min: 78 }, { axis: "FISC", min: 70 }, { axis: "SEC", max: 30 }, { axis: "CULT", min: 65 }],
    },
    {
      id: "communitarian_left",
      name: "共同体经济左翼",
      summary: "你经济上偏社会国家和公共投资，但在移民、文化或安全议题上更重视边界、共同体和秩序。",
      tags: ["经济左翼", "共同体", "边界"],
      rules: [{ axis: "ECO", min: 65 }, { axis: "FISC", min: 62 }, { axis: "MIG", max: 42 }, { axis: "CULT", max: 48 }],
    },
    {
      id: "regional_modernizer",
      name: "地区公共投资现代化派",
      summary: "你把德国问题更多理解为国家能力、地区差距、基础设施和教育机会问题，而不是单纯文化阵营问题。",
      tags: ["地区团结", "现代化", "公共投资"],
      rules: [{ axis: "REG", min: 72 }, { axis: "MOD", min: 70 }, { axis: "FISC", min: 58 }],
    },
    {
      id: "mixed",
      name: "混合型德国选民",
      summary: "你的回答跨越德国政治的多条裂缝，最好查看维度条、对照视角和党派距离拆解，而不是只看一个标签。",
      tags: ["混合取向", "议题分裂", "维度拆解"],
      rules: [],
    },
  ];

  const issueExplanations = topics.map((topic) => ({
    id: topic.id,
    title: topic.title,
    axis: topic.axis,
    summary: topic.summary,
    examples: questions.filter((question) => question.topic === topic.id).slice(0, 3).map((question) => question.textZh),
  }));

  const sources = [
    {
      title: "德国政治光谱测试分享页规格草案",
      url: "https://chatgpt.com/share/6a380812-4ec4-83ee-917b-4cfdbd365532",
      note: "题库结构、10 维模型和首版功能规格来源。",
    },
    {
      title: "Federal Returning Officer - 2025 Bundestag election results",
      url: "https://www.bundeswahlleiterin.de/en/bundestagswahlen/2025/ergebnisse.html",
      note: "德国 2025 联邦议院选举结果官方入口。",
    },
    {
      title: "Deutscher Bundestag - Distribution of seats",
      url: "https://www.bundestag.de/en/parliament/plenary/distributionofseats",
      note: "联邦议院席位结构入口。",
    },
    {
      title: "bpb - Wer steht zur Wahl? Bundestagswahl 2025",
      url: "https://www.bpb.de/themen/parteien/wer-steht-zur-wahl/bundestagswahl-2025/",
      note: "2025 参选党资料入口，用于小党参照范围。",
    },
    {
      title: "Wahl-O-Mat Bundestagswahl 2025",
      url: "https://www.bpb.de/themen/wahl-o-mat/bundestagswahl-2025/",
      note: "政策题目和党派回应的公开资料入口。",
    },
    {
      title: "Chapel Hill Expert Survey 2024",
      url: "https://www.chesdata.eu/2024-chapel-hill-expert-survey-ches",
      note: "欧洲党派专家调查，可用于后续坐标校准。",
    },
    {
      title: "Manifesto Project Dataset 2025a",
      url: "https://manifesto-project.wzb.eu/datasets",
      note: "政党宣言编码资料，可用于后续文本校准。",
    },
    {
      title: "Federal Office for the Protection of the Constitution",
      url: "https://www.verfassungsschutz.de/",
      note: "涉及极端主义分类、法律争议和官方表述时仅作为公开资料入口。",
    },
  ];

  return {
    version,
    axes,
    topics,
    questions,
    profiles,
    modes,
    defaultWeights,
    regionViews,
    coordinateViews,
    matchViews,
    coalitionViews,
    resultLabels,
    issueExplanations,
    sources,
    methodNote: "本测试所有计算在浏览器本地完成，不上传原始答案。党派/派系坐标是建站用首版启发式估计，不代表官方立场，不构成投票建议；涉及 AfD、极端主义分类、党禁等敏感法律政治议题时，以公开资料和后续校准为准。",
  };
})();
