window.JP_SPECTRUM_DATA = {
  meta: {
    title: "日本政治・社会価値観スペクトラム診断",
    version: "2026.06 prototype",
    updated: "2026-06-13",
    disclaimer:
      "结果只表示你在本题库中的价值坐标和政策距离，不构成投票建议、政治建议或价值判断。",
  },

  scale: [
    { value: 1, label: "1", title: "强烈不同意" },
    { value: 2, label: "2", title: "不同意" },
    { value: 3, label: "3", title: "有点不同意" },
    { value: 4, label: "4", title: "略不同意" },
    { value: 5, label: "5", title: "中立 / 不确定" },
    { value: 6, label: "6", title: "略同意" },
    { value: 7, label: "7", title: "有点同意" },
    { value: 8, label: "8", title: "同意" },
    { value: 9, label: "9", title: "强烈同意" },
  ],

  modes: {
    quick: {
      key: "quick",
      label: "40 题快速版",
      perAxis: 4,
      description: "先看大致坐标，移动端也能顺手完成。",
    },
    standard: {
      key: "standard",
      label: "70 题标准版",
      perAxis: 7,
      description: "覆盖主要议题，结果稳定性更好。",
    },
    full: {
      key: "full",
      label: "100 题深度版",
      perAxis: 10,
      description: "完整题库，适合政治兴趣和研究型用户。",
    },
  },

  dimensions: [
    {
      id: "welfare",
      short: "福利",
      name: "再分配与福利国家",
      negative: "福利再分配",
      positive: "市场激励",
      color: "#d94f45",
      summary: "公共服务、最低工资、贫困救助、儿童与老年保障之间的取舍。",
    },
    {
      id: "fiscal",
      short: "财政",
      name: "财政扩张 vs 财政稳健",
      negative: "扩张减税",
      positive: "债务稳健",
      color: "#b87900",
      summary: "通胀、消费税、国债、社会保障可持续性和财政纪律。",
    },
    {
      id: "industry",
      short: "产业",
      name: "产业政策 vs 市场竞争",
      negative: "国家投资",
      positive: "竞争改革",
      color: "#2f8f6f",
      summary: "半导体、AI、防卫产业、供应链安全和规制改革。",
    },
    {
      id: "security",
      short: "安保",
      name: "安全正常化与宪法修正",
      negative: "和平约束",
      positive: "安全正常化",
      color: "#4157b7",
      summary: "第九条、自卫队、防卫费、反击能力和集体自卫权。",
    },
    {
      id: "diplomacy",
      short: "外交",
      name: "外交路线与区域秩序",
      negative: "对话自主",
      positive: "同盟威慑",
      color: "#5c6f84",
      summary: "美日同盟、印太合作、中国与韩国关系、台湾海峡和经济安全。",
    },
    {
      id: "immigration",
      short: "外国人",
      name: "移民、外国人和国民共同体",
      negative: "开放共生",
      positive: "限制管制",
      color: "#2487a6",
      summary: "劳动力短缺、长期居留、多文化服务、福利条件和土地管制。",
    },
    {
      id: "social",
      short: "社会",
      name: "社会自由、性别与家庭制度",
      negative: "社会自由",
      positive: "传统连续",
      color: "#a24da3",
      summary: "同性婚姻、夫妇别姓、皇位继承、性别平等和家庭制度。",
    },
    {
      id: "energy",
      short: "能源",
      name: "能源、气候与核能",
      negative: "脱碳慎核",
      positive: "能源安全",
      color: "#4c9a3f",
      summary: "可再生能源、核能重启、电价、产业成本和 2050 净零路径。",
    },
    {
      id: "local",
      short: "地方",
      name: "中央集权 vs 地方分权 / 行政改革",
      negative: "地方改革",
      positive: "中央协调",
      color: "#d66b2d",
      summary: "地方自治、中央官僚、行政精简、数字化和区域公共服务均等。",
    },
    {
      id: "liberty",
      short: "自由",
      name: "国家权威、公共秩序与公民自由",
      negative: "公民自由",
      positive: "国家秩序",
      color: "#1f7a8c",
      summary: "隐私、抗议、信息公开、国家安全、平台治理和行政裁量。",
    },
  ],

  questions: [
    { id: "W01", dimension: "welfare", direction: -1, issue: "物价与救助", text: "物价上涨时期，政府应优先补贴中低收入家庭，即使财政负担增加。" },
    { id: "W02", dimension: "welfare", direction: -1, issue: "劳动", text: "日本应进一步提高最低工资，以改善非正规劳动者的处境。" },
    { id: "W03", dimension: "welfare", direction: -1, issue: "育儿", text: "儿童津贴和育儿服务应更接近普遍公共服务，而不是只面向极低收入家庭。" },
    { id: "W04", dimension: "welfare", direction: -1, issue: "医疗护理", text: "医疗和长期护理的公共投入应继续扩大，即使需要更多税收支持。" },
    { id: "W05", dimension: "welfare", direction: -1, issue: "雇佣", text: "政府应加强对非正规雇佣者的社会保险、休假和职业培训保障。" },
    { id: "W06", dimension: "welfare", direction: 1, issue: "现金给付", text: "福利政策应更集中在严格审查后的困难人群，而不是扩大现金给付范围。" },
    { id: "W07", dimension: "welfare", direction: 1, issue: "就业流动", text: "改善生活的关键是让工资和岗位更自由流动，而不是保护既有雇佣关系。" },
    { id: "W08", dimension: "welfare", direction: 1, issue: "养老金", text: "为了控制下一代负担，养老金给付或领取年龄改革是不可避免的。" },
    { id: "W09", dimension: "welfare", direction: 1, issue: "地方服务", text: "人口减少地区的公共服务如果难以维持，应优先整合网点而不是继续补贴原规模。" },
    { id: "W10", dimension: "welfare", direction: 1, issue: "自助", text: "个人储蓄、职业转换和家庭自助应比扩大公共福利承担更大责任。" },

    { id: "F01", dimension: "fiscal", direction: -1, issue: "消费税", text: "在生活成本压力较大时，暂时降低消费税是可以接受的，即使赤字扩大。" },
    { id: "F02", dimension: "fiscal", direction: -1, issue: "国债", text: "为了工资、育儿和基础设施，政府可以更积极发行国债。" },
    { id: "F03", dimension: "fiscal", direction: -1, issue: "投资", text: "少子化和地方衰退需要现在投入，不能等到财政完全平衡后再行动。" },
    { id: "F04", dimension: "fiscal", direction: -1, issue: "宏观政策", text: "日本应继续使用财政和货币政策支持需求，直到稳定的工资增长形成。" },
    { id: "F05", dimension: "fiscal", direction: -1, issue: "减税", text: "实际工资承压时，减税和补贴比增税或支出削减更合适。" },
    { id: "F06", dimension: "fiscal", direction: 1, issue: "债务", text: "考虑到高债务和老龄化，日本应把财政可持续性放在更高优先级。" },
    { id: "F07", dimension: "fiscal", direction: 1, issue: "社保", text: "如果社会保障支出继续增长，提高税收或保险费是现实选择。" },
    { id: "F08", dimension: "fiscal", direction: 1, issue: "预算", text: "没有稳定财源的永久性支出承诺应尽量避免。" },
    { id: "F09", dimension: "fiscal", direction: 1, issue: "通胀", text: "通胀环境下，政府应减少刺激性支出，避免加重价格压力。" },
    { id: "F10", dimension: "fiscal", direction: 1, issue: "税制", text: "消费税作为稳定财源应维持，必要时可以小幅渐进调整。" },

    { id: "I01", dimension: "industry", direction: -1, issue: "半导体", text: "半导体、AI 和量子技术应得到政府长期补贴和产业规划。" },
    { id: "I02", dimension: "industry", direction: -1, issue: "供应链", text: "经济安全需要国家保护关键供应链，而不能完全依赖自由贸易。" },
    { id: "I03", dimension: "industry", direction: -1, issue: "采购", text: "政府采购应更多支持国内关键技术和战略产业。" },
    { id: "I04", dimension: "industry", direction: -1, issue: "地方产业", text: "地方传统产业转型需要公共资金和政策扶持，而不是只交给市场淘汰。" },
    { id: "I05", dimension: "industry", direction: -1, issue: "防卫产业", text: "防卫、太空和网络安全产业应通过公私合作计划加速发展。" },
    { id: "I06", dimension: "industry", direction: 1, issue: "政府选择", text: "政府不应过度挑选未来产业赢家，市场竞争更能发现真正有效的方向。" },
    { id: "I07", dimension: "industry", direction: 1, issue: "规制改革", text: "提高生产率的关键是放松规制、促进创业和增加新进入者。" },
    { id: "I08", dimension: "industry", direction: 1, issue: "补贴依赖", text: "长期补贴容易让企业依赖政府，削弱自我改革动力。" },
    { id: "I09", dimension: "industry", direction: 1, issue: "竞争", text: "外资和海外竞争对日本产业升级是必要压力。" },
    { id: "I10", dimension: "industry", direction: 1, issue: "退出机制", text: "低效率企业退出和资源重新配置，比维持既有企业数量更重要。" },

    { id: "S01", dimension: "security", direction: 1, issue: "修宪", text: "宪法应明确写入自卫队的存在和职责。" },
    { id: "S02", dimension: "security", direction: 1, issue: "防卫能力", text: "日本应继续提高防卫能力，以应对周边安全环境变化。" },
    { id: "S03", dimension: "security", direction: 1, issue: "集体自卫", text: "在盟友受到攻击且日本安全受影响时，日本应能更灵活行使集体自卫权。" },
    { id: "S04", dimension: "security", direction: 1, issue: "反击能力", text: "在严格条件下，保有反击能力可以提高威慑力。" },
    { id: "S05", dimension: "security", direction: 1, issue: "装备出口", text: "防卫装备出口和共同开发规则可以适度放宽，以加强安全合作。" },
    { id: "S06", dimension: "security", direction: -1, issue: "第九条", text: "宪法第九条对限制军事化仍有重要现实意义。" },
    { id: "S07", dimension: "security", direction: -1, issue: "外交优先", text: "日本应把外交、危机沟通和信任建设置于军备扩张之前。" },
    { id: "S08", dimension: "security", direction: -1, issue: "预算取舍", text: "防卫费提高不应挤压教育、福利和地方财政。" },
    { id: "S09", dimension: "security", direction: -1, issue: "海外行动", text: "自卫队海外活动应受到比现在更严格的国会和法律限制。" },
    { id: "S10", dimension: "security", direction: -1, issue: "修宪程序", text: "宪法修正应以跨党派和广泛社会共识为前提，不能只靠短期多数推动。" },

    { id: "D01", dimension: "diplomacy", direction: 1, issue: "美日同盟", text: "日本应进一步强化美日同盟和印太安全合作。" },
    { id: "D02", dimension: "diplomacy", direction: 1, issue: "台湾海峡", text: "台湾海峡和平稳定与日本安全直接相关。" },
    { id: "D03", dimension: "diplomacy", direction: 1, issue: "经济安全", text: "对来自威权国家的经济胁迫和技术依赖，日本应采取更强的防范政策。" },
    { id: "D04", dimension: "diplomacy", direction: 1, issue: "制裁合作", text: "在重大国际危机中，日本应更积极配合民主国家的制裁和出口管制。" },
    { id: "D05", dimension: "diplomacy", direction: 1, issue: "海洋安全", text: "东海和南海的海洋安全需要更明确的威慑和执法合作。" },
    { id: "D06", dimension: "diplomacy", direction: -1, issue: "战略自主", text: "日本应避免在中美竞争中过度选边，保留更多战略自主空间。" },
    { id: "D07", dimension: "diplomacy", direction: -1, issue: "邻国关系", text: "改善与中国、韩国的长期关系，应优先于象征性对抗。" },
    { id: "D08", dimension: "diplomacy", direction: -1, issue: "美国政治", text: "日本安全政策不应过度依赖美国国内政治的稳定性。" },
    { id: "D09", dimension: "diplomacy", direction: -1, issue: "历史问题", text: "历史和解、民间交流与文化互信是区域安全的重要基础。" },
    { id: "D10", dimension: "diplomacy", direction: -1, issue: "经贸交流", text: "贸易、旅游和教育交流可以降低外交安全风险，应尽量维持开放。" },

    { id: "M01", dimension: "immigration", direction: -1, issue: "劳动力", text: "面对劳动力短缺，日本应扩大外国劳动者的长期居留路径。" },
    { id: "M02", dimension: "immigration", direction: -1, issue: "家庭团聚", text: "长期纳税和生活的外国劳动者，应更容易获得稳定身份和家庭团聚机会。" },
    { id: "M03", dimension: "immigration", direction: -1, issue: "公共服务", text: "地方政府应投入更多资源提供多语言行政、教育和医疗信息。" },
    { id: "M04", dimension: "immigration", direction: -1, issue: "反歧视", text: "住房、就业和教育中的国籍或族裔歧视，应受到更明确的制度约束。" },
    { id: "M05", dimension: "immigration", direction: -1, issue: "身份制度", text: "永住和入籍规则应更加透明，让长期居民能预期自己的未来。" },
    { id: "M06", dimension: "immigration", direction: 1, issue: "福利条件", text: "外国居民获得公共福利的条件应比日本国民更严格。" },
    { id: "M07", dimension: "immigration", direction: 1, issue: "土地房产", text: "外国人购买敏感地区土地或房产应受到更多限制。" },
    { id: "M08", dimension: "immigration", direction: 1, issue: "接收速度", text: "外国劳动者接收速度应受语言教育、住房和社区承载能力限制。" },
    { id: "M09", dimension: "immigration", direction: 1, issue: "执法", text: "对逾期居留和违反在留资格的行为，应加强执法和遣返程序。" },
    { id: "M10", dimension: "immigration", direction: 1, issue: "同化", text: "长期居留者应更明确地学习日语、遵守地方习惯并融入日本社会规范。" },

    { id: "C01", dimension: "social", direction: -1, issue: "同性婚姻", text: "日本应承认同性婚姻或提供与婚姻实质等同的制度保障。" },
    { id: "C02", dimension: "social", direction: -1, issue: "夫妇别姓", text: "已婚夫妇应可以选择保留各自姓氏。" },
    { id: "C03", dimension: "social", direction: -1, issue: "皇位继承", text: "皇位继承制度应开放讨论女性天皇或女系继承的可能性。" },
    { id: "C04", dimension: "social", direction: -1, issue: "性别平等", text: "为了改善女性职业发展，政党、企业和大学可以采用更积极的性别平等目标。" },
    { id: "C05", dimension: "social", direction: -1, issue: "教育", text: "学校应更系统地提供性教育、反骚扰教育和多样性教育。" },
    { id: "C06", dimension: "social", direction: 1, issue: "家庭制度", text: "婚姻和家庭制度的连续性，比快速适应新的价值观更重要。" },
    { id: "C07", dimension: "social", direction: 1, issue: "皇室传统", text: "皇位继承应维持男系继承原则，以保护皇室传统。" },
    { id: "C08", dimension: "social", direction: 1, issue: "学校仪式", text: "学校教育应更重视国旗、国歌、传统节日和共同体意识。" },
    { id: "C09", dimension: "social", direction: 1, issue: "社区", text: "家庭与性别问题应更多通过地方社区和私人协商解决，而不是国家法律改革。" },
    { id: "C10", dimension: "social", direction: 1, issue: "社会变化", text: "社会价值变化过快可能削弱共同规范，因此制度改革应更谨慎。" },

    { id: "E01", dimension: "energy", direction: -1, issue: "可再生能源", text: "即使短期成本上升，日本也应更快投资可再生能源、电网和储能。" },
    { id: "E02", dimension: "energy", direction: -1, issue: "核能", text: "日本应长期减少对核电的依赖，而不是把核电重新作为核心电源。" },
    { id: "E03", dimension: "energy", direction: -1, issue: "化石能源", text: "煤炭和天然气发电应更快退出，以推动 2050 净零目标。" },
    { id: "E04", dimension: "energy", direction: -1, issue: "地方同意", text: "核电站重启必须以更严格的地方同意和避难计划为前提。" },
    { id: "E05", dimension: "energy", direction: -1, issue: "碳定价", text: "碳定价和排放交易应更有力度，让企业承担排放成本。" },
    { id: "E06", dimension: "energy", direction: 1, issue: "重启", text: "通过安全审查的核反应堆应尽快重启，以稳定电力供应。" },
    { id: "E07", dimension: "energy", direction: 1, issue: "进口依赖", text: "能源进口依赖过高，因此核能对日本能源安全仍然必要。" },
    { id: "E08", dimension: "energy", direction: 1, issue: "电价", text: "产业竞争力和家庭电费应优先于过快提高减排标准。" },
    { id: "E09", dimension: "energy", direction: 1, issue: "技术中立", text: "脱碳政策应保持技术中立，把核能、氢能和碳捕集都纳入选择。" },
    { id: "E10", dimension: "energy", direction: 1, issue: "韧性", text: "自然灾害和国际危机下，稳定基载电源比单一依赖可再生能源更可靠。" },

    { id: "L01", dimension: "local", direction: -1, issue: "财权", text: "地方政府应拥有更多税源和财政决策权，而不是依赖中央补助。" },
    { id: "L02", dimension: "local", direction: -1, issue: "行政精简", text: "人口减少地区应推进议会、行政机构和公共设施的合并精简。" },
    { id: "L03", dimension: "local", direction: -1, issue: "特区", text: "日本应允许更多地方特区试验教育、医疗、交通和数字治理改革。" },
    { id: "L04", dimension: "local", direction: -1, issue: "东京集中", text: "为了缓解东京一极集中，地方自治和区域核心城市应获得更多政策空间。" },
    { id: "L05", dimension: "local", direction: -1, issue: "数字政府", text: "行政数字化应打破中央部会纵向分割，优先以居民体验重组流程。" },
    { id: "L06", dimension: "local", direction: 1, issue: "服务均等", text: "教育、医疗和防灾等基本服务需要全国统一标准，不能过度交给地方差异。" },
    { id: "L07", dimension: "local", direction: 1, issue: "地区差距", text: "过度地方分权可能扩大富裕地区和衰退地区的差距。" },
    { id: "L08", dimension: "local", direction: 1, issue: "危机治理", text: "灾害、感染症和老龄化政策应由中央政府更强力统筹。" },
    { id: "L09", dimension: "local", direction: 1, issue: "行政能力", text: "削减公务员和议员数量不应以削弱公共服务能力为代价。" },
    { id: "L10", dimension: "local", direction: 1, issue: "政策协调", text: "全国性政党和中央部会更适合协调广域交通、能源和财政政策。" },

    { id: "A01", dimension: "liberty", direction: -1, issue: "信息公开", text: "政府文件、政治资金和政策形成过程应有更强的信息公开义务。" },
    { id: "A02", dimension: "liberty", direction: -1, issue: "隐私", text: "数字行政和安全政策不应以便利为理由过度收集个人数据。" },
    { id: "A03", dimension: "liberty", direction: -1, issue: "抗议", text: "即使造成不便，和平抗议和街头表达也应受到充分保护。" },
    { id: "A04", dimension: "liberty", direction: -1, issue: "媒体", text: "公共媒体和学校教育应保持更强的政治中立与编辑独立。" },
    { id: "A05", dimension: "liberty", direction: -1, issue: "司法", text: "刑事司法应更加重视透明、辩护权和对行政权力的制衡。" },
    { id: "A06", dimension: "liberty", direction: 1, issue: "公共秩序", text: "为了公共秩序，政府可以对示威地点、时间和扩音设备作更严格限制。" },
    { id: "A07", dimension: "liberty", direction: 1, issue: "国家机密", text: "国家安全和外交谈判需要一定保密空间，不能全部公开。" },
    { id: "A08", dimension: "liberty", direction: 1, issue: "平台治理", text: "面对虚假信息和网络煽动，政府应对平台内容治理提出更强要求。" },
    { id: "A09", dimension: "liberty", direction: 1, issue: "行政裁量", text: "警察和行政机关需要较大裁量权，才能迅速处理治安和安全风险。" },
    { id: "A10", dimension: "liberty", direction: 1, issue: "义务", text: "学校和职场应更明确强调公共义务、规则意识和对共同体的责任。" },
  ],

  partyPositions: [
    {
      id: "ldp",
      name: "自民党",
      note: "主流保守、安保正常化、产业政策与现实主义财政的混合参考点。",
      scores: { welfare: 18, fiscal: 28, industry: -32, security: 72, diplomacy: 62, immigration: 28, social: 55, energy: 58, local: 22, liberty: 34 },
    },
    {
      id: "cdp",
      name: "立宪民主党",
      note: "社会自由、福利重视、安保较克制的中间偏左参考点。",
      scores: { welfare: -48, fiscal: -8, industry: -8, security: -34, diplomacy: -18, immigration: -24, social: -66, energy: -42, local: -16, liberty: -52 },
    },
    {
      id: "komeito",
      name: "公明党",
      note: "中道福利、和平主义传统与联合执政现实主义之间的参考点。",
      scores: { welfare: -36, fiscal: 8, industry: -10, security: -8, diplomacy: -12, immigration: -18, social: -18, energy: 8, local: 4, liberty: -22 },
    },
    {
      id: "ishin",
      name: "日本维新会",
      note: "行政改革、地方分权、市场改革与安保正常化的参考点。",
      scores: { welfare: 24, fiscal: 34, industry: 20, security: 46, diplomacy: 34, immigration: 12, social: -8, energy: 26, local: -76, liberty: 8 },
    },
    {
      id: "dpp",
      name: "国民民主党",
      note: "减税、工资、产业现实主义和安保现实主义的参考点。",
      scores: { welfare: -12, fiscal: -36, industry: -22, security: 42, diplomacy: 36, immigration: 4, social: -6, energy: 36, local: -14, liberty: 0 },
    },
    {
      id: "jcp",
      name: "日本共产党",
      note: "强福利、反修宪、反核和公民自由取向的左翼参考点。",
      scores: { welfare: -82, fiscal: -48, industry: -34, security: -86, diplomacy: -62, immigration: -48, social: -76, energy: -86, local: -24, liberty: -78 },
    },
    {
      id: "reiwa",
      name: "令和新选组",
      note: "反紧缩、福利扩张、减税与安保克制的民粹左翼参考点。",
      scores: { welfare: -86, fiscal: -82, industry: -48, security: -66, diplomacy: -46, immigration: -36, social: -66, energy: -78, local: -16, liberty: -62 },
    },
    {
      id: "sanseito",
      name: "参政党",
      note: "国民优先、社会保守、移民限制和国家主权强调的参考点。",
      scores: { welfare: 6, fiscal: -28, industry: -10, security: 66, diplomacy: 46, immigration: 84, social: 82, energy: 24, local: 8, liberty: 58 },
    },
    {
      id: "hoshu",
      name: "日本保守党",
      note: "强安保、传统保守、移民限制和国家秩序强调的参考点。",
      scores: { welfare: 20, fiscal: 12, industry: -12, security: 86, diplomacy: 72, immigration: 90, social: 90, energy: 62, local: 20, liberty: 64 },
    },
    {
      id: "sdp",
      name: "社民党",
      note: "和平主义、福利、人权和反核取向的左翼参考点。",
      scores: { welfare: -76, fiscal: -38, industry: -30, security: -92, diplomacy: -64, immigration: -44, social: -78, energy: -88, local: -20, liberty: -74 },
    },
  ],

  sources: [
    {
      title: "OECD Economic Surveys: Japan 2024",
      url: "https://www.oecd.org/en/publications/oecd-economic-surveys-japan-2024_41e807f9-en.html",
      note: "财政、通胀、老龄化、生产率、移民与能源约束。",
    },
    {
      title: "Japan Ministry of Defense: Defense Budget",
      url: "https://www.mod.go.jp/en/d_act/d_budget/index.html",
      note: "FY2026 防卫预算与防卫能力强化资料入口。",
    },
    {
      title: "Agency for Natural Resources and Energy: 7th Strategic Energy Plan",
      url: "https://www.enecho.meti.go.jp/en/category/others/basic_plan/",
      note: "2025 年第七次能源基本计划、2040 能源供需展望。",
    },
    {
      title: "Specified Skilled Worker Program",
      url: "https://www.ssw.go.jp/en/",
      note: "特定技能制度与外国劳动者接收信息。",
    },
    {
      title: "OECD International Migration Outlook 2025: Japan",
      url: "https://www.oecd.org/en/publications/international-migration-outlook-2025_ae26c893-en/full-report/japan_ccc89a8d.html",
      note: "长期移民、留学生、临时劳动者和技能实习背景。",
    },
  ],
};
